#!/bin/bash

lead='### BEGIN LOLSSH GENERATED CONTENT'
tail='### END LOLSSH GENERATED CONTENT'

update_file() {
    contentsfile=$1
    targetfile=$2
    sed --posix -i.bak -e "/^${lead}$/,/$tail/{ /^${lead}$/{p; r ${contentsfile}
            }; /^${tail}$/p; d }" ${targetfile}
}

create_file() {
    contentsfile=$1
    targetfile=$2
    echo -e "\n${lead}\n$( cat ${contentsfile} )\n${tail}" >> ${targetfile}
}

if egrep --quiet "$lead" ~/.ssh/config; then
    echo "Updating ssh-config entry"
    update_file ./conf/ssh-config ~/.ssh/config
else
    echo "Creating ssh-config entry"
    if [ ! -d ~/.ssh/ ]; then
        mkdir ~/.ssh/
    fi
    if [ ! -e ~/.ssh/config ]; then
        touch ~/.ssh/config
        chmod 700 ~/.ssh/config
    fi
    create_file ./conf/ssh-config ~/.ssh/config
fi

if ! grep --quiet templatedir ~/.gitconfig; then
    echo "Creating gitconfig"
    if [ ! -e ~/.gitconfig ]; then
        touch ~/.gitconfig
    fi
    create_file ./conf/gitconfig ~/.gitconfig
fi

templatedir=$( grep templatedir ~/.gitconfig | cut -d'=' -f2 | xargs echo )
if [ ! -d ${templatedir}/hooks ]; then
    mkdir ${templatedir}/hooks
fi
if [ ! -e ${templatedir}/hooks/post-commit ]; then
    echo "Creating new git post-commit hook in ${templatedir}"
    create_file ./conf/post-commit ${temlatedir}/hooks/post-commit
else
    echo "Updating git post-commit hook in ${templatedir}"
    update_file ./conf/post-commit ${templatedir}/hooks/post-commit
fi

echo "Checking and removing any existing lolcommits hook in post-commit hook"
sed -i.bak '/^${lead}$/,/^${tail}$/d' ${templatedir}/hooks/post-commit
